-- THIS IS THE WAY TO WRITE COMMENTS IN SINGLE LINE IN SQL
/*
THIS IS THE WAY TO WRITE THE COMMENTS IN MULTIPLE LINES IN SQL
*/            

CREATE DATABASE FIRSTCLASS;
-- WE CAN MAKE MULTIPLE DATABASE AND USE SINGLE AS YOU CAN SEE NOW 
CREATE DATABASE TANISHK;

USE FIRSTCLASS;

-- DATA IS STORED IN FORM OF TABLE
CREATE TABLE STUDENT 
(
-- HERE WE HAVE TO WRITE THE ATTRIBUTES OF THE TABLE
ID INT,
NAME VARCHAR(50),
CGPA float
);

INSERT INTO STUDENT VALUES (1,'PEN',7.8); -- THIS IS THE WAY TO INSERT VALUES INTO THE TABLE
INSERT INTO STUDENT VALUES (2,'PENCIL',8.1);
INSERT INTO STUDENT VALUES (3,'SHARPNER',8.5);
INSERT INTO STUDENT VALUES (4,'ERASER',9);

SELECT * FROM STUDENT ; -- HERE * REPRESENTS ALL  
-- NOW YOU WILL SE REPRESENTATION WITH CONDITIONS
SELECT * FROM STUDENT WHERE CGPA > 8.1;
SELECT ID FROM STUDENT WHERE CGPA > 8.1;

-- THIS WILL DESCRIBE THE STUDENT TABLE
DESC STUDENT;  

-- TO ADD COLUMN IN TABLE THIS IS THE STATEMENT 
ALTER TABLE STUDENT ADD COLUMN DOB DATE;
INSERT INTO STUDENT VALUES (5,"BOX",9.5,"2005-10-1");

-- TO UPDATES COLUMN WE NEED TO DO THIS 
SET SQL_SAFE_UPDATES=0;
UPDATE STUDENT SET DOB = "2005-10-2" WHERE NAME = "PENCIL";


-- DELETE FROM STUDENT WHERE ID = 1;    THIS IS THW WAY TO DELETE THE ROW