CREATE DATABASE LAB_2;
USE LAB_2;

CREATE TABLE EMPLOYEE (
EmployeeId VARCHAR(50) ,
Lname VARCHAR(50) NOT NULL,
Fname VARCHAR(50) NOT NULL,
PositionId VARCHAR(50) DEFAULT "1234XXXX",
Supervisor VARCHAR(50) NOT NULL,
HireDate DATE NOT NULL,
Salary INT ,
Commission INT ,
DeptId VARCHAR (50) NOT NULL,
QualId VARCHAR (50) NOT NULL,
PRIMARY KEY (EmployeeId) 
);
INSERT INTO EMPLOYEE VALUES ("330201","GUPTA","AACHARYA","NORMAL","YES","2022-12-06",25000,12000,"55001","YUOP2345");
INSERT INTO EMPLOYEE VALUES ("330302","AGARWAL","DAKSH","MANAGER","NO","2023-03-04",50000,32000,"55002","SFDH7543");
INSERT INTO EMPLOYEE VALUES ("330403","KHANDELWAL","ARVE","CASHIER","YES","2022-04-03",75000,21000,"55003","VBJZD3245");
INSERT INTO EMPLOYEE VALUES ("330504","MODI","SAKSHAM","ACCOUNTANT","NO","2024-07-02",85000,18000,"55004","ASD234543");
INSERT INTO EMPLOYEE VALUES ("330605","KATARIA","KAPIL","CLERK","NO","2020-08-01",95000,15000,"55005","SBDG5543");

SELECT * FROM EMPLOYEE;

CREATE TABLE POSITION (
PositionId VARCHAR(50), 
PosDesc VARCHAR (50) NOT NULL,
PRIMARY KEY (PositionId)
);
INSERT INTO POSITION VALUES ("CASHIER","HANDELS CASH");
INSERT INTO POSITION VALUES ("MANAGER","OPENS ACCOUNT");
INSERT INTO POSITION VALUES ("ACCOUNTANT","HANDELS STATEMENT");
INSERT INTO POSITION VALUES ("GUARD","HANDELS WITH SECRUITY");
INSERT INTO POSITION VALUES ("SENIOR MANAGER","DEALS WITH BRANCH");
SELECT * FROM POSITION;


CREATE TABLE DEPT 
(
DeptId VARCHAR (50),
DeptName VARCHAR (50)NOT NULL,
Location VARCHAR (50) NOT NULL,
EmployeeId VARCHAR (50) DEFAULT "1234XXXX",
PRIMARY KEY (DeptId) 
);
INSERT INTO DEPT VALUES ("CHSHSJFH","SCHOOL OF ELECTRONICS","CAMPUS-12","ASDWQF");
INSERT INTO DEPT VALUES ("PUJKFDS","SCHOOL OF COMPUTER SCIENCE","CAMPUS-14","PODFIY");
INSERT INTO DEPT VALUES ("NXCNNC","SCHOOL OF MECHANICAL","CAMPUS-18","KFDFDFF");
INSERT INTO DEPT VALUES ("WEIRY9I","SCHOOL OF AEROSPACE","CAMPUS-13","QEFEQQ");
INSERT INTO DEPT VALUES ("NCXDJEW","SCHOOL OF CIVIL","CAMPUS-6","VERIVE");
SELECT * FROM DEPT;

CREATE TABLE QUALIFICATION
(
QualId VARCHAR(50),
QualDesc VARCHAR(50) NOT NULL ,
PRIMARY KEY (QualId)
);
INSERT INTO QUALIFICATION VALUES ("11th Class"," BASIC JOINT ENTRANCE EXAM STUDIES");
INSERT INTO QUALIFICATION VALUES ("12th Class"," HIGHER JOINT ENTRANCE EXAM STUDIES");
INSERT INTO QUALIFICATION VALUES ("1st Year","BASICS OF 11th AND 12th CLASS");
INSERT INTO QUALIFICATION VALUES ("2nd Year","Core Subjects Of Engineering");
INSERT INTO QUALIFICATION VALUES ("3rd Year","Placements And Training ");
SELECT * FROM QUALIFICATION;

CREATE TABLE EMPLEVEL(
LevelNo INT ,
LowSalary INT,
HighSalary INT NOT NULL,
PRIMARY KEY (LevelNo),
CHECK (LowSalary<50000)
); 
INSERT INTO EMPLEVEL VALUES (1,13500,3400000);
INSERT INTO EMPLEVEL VALUES (2,25000,6780000);
INSERT INTO EMPLEVEL VALUES (3,37000,8760000);
INSERT INTO EMPLEVEL VALUES (4,48000,1230000);
INSERT INTO EMPLEVEL VALUES (5,35000,3090000);
SELECT * FROM EMPLEVEL;

CREATE TABLE DEPENDENT (
EmployeeId VARCHAR(50),
DependentId VARCHAR(50) NOT NULL,
DepDOB DATE ,
Relation VARCHAR(50) NOT NULL,
PRIMARY KEY (EmployeeId)
);
INSERT INTO DEPENDENT VALUES("QWERTY","POIUYT","2004-12-10","BROTHER");
INSERT INTO DEPENDENT VALUES("LKJHG","ASDFG","2009-10-07","SISTER");
INSERT INTO DEPENDENT VALUES("ZXCVB","MNBVC","2002-08-11","MOTHER");
INSERT INTO DEPENDENT VALUES("EDCRFV","QAZWSX","2007-06-01","GRANDMOTHER");
INSERT INTO DEPENDENT VALUES("TGBPLK","YHNUJM","2003-04-06","FATHER");
SELECT * FROM DEPENDENT;