CREATE DATABASE LAB6;
USE LAB3;	
USE LAB2;

SELECT D.DEPTNAME FROM EMPLOYEE E INNER JOIN DEPARTMENT D ON E.DEPTID = D.DEPTID WHERE E.Fname = "SAKSHAM" AND E.Lname ="MODI" ;
SELECT * FROM DEPARTMENT ;

SELECT S.Fname, S.Lname FROM EMPLOYEE E JOIN EMPLOYEE S ON E.Supervisor = S.EmployeeId WHERE E.EmployeeId = "2330349";
SELECT * FROM EMPLOYEE;

CREATE TABLE EMP30 AS SELECT NAME , ID FROM EMPLOYEE WHERE DEPTID=2;



